builders:
  txt_file_builder:
    import: "package:dart_helpers/builder.dart"
    builder_factories: ["txtFileBuilder"]
    build_extensions: {r"$package$": ["lib/gen/app_version.dart"]}
    auto_apply: root_package
    build_to: source
    defaults:
      options:
        enabled: false
