builders:
  app_version:
    import: "package:dart_helpers/builder.dart"
    builder_factories: ["appVersionBuilder"]
    build_extensions: {r"$package$": ["lib/gen/app_version.dart"]}
    auto_apply: root_package
    build_to: source
    defaults:
      options:
        enabled: true
