name: dart_helpers
description: A dart package with useful helpers
version: 1.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  collection: ^1.18.0

dev_dependencies:
  test: ^1.24.0
  build_runner: ^2.4.11
  flutter_lints: ^5.0.0