name: dart_helpers
description: A dart package with useful helpers
version: 1.0.1

environment:
  sdk: ^3.5.3

dependencies:
  dio: ^5.8.0+1
  collection:
  path: ^1.8.0
  encrypt: ^5.0.3
  crypto: ^3.0.6


dev_dependencies:
  test: ^1.24.0
  build_runner: ^2.4.11
  flutter_lints: ^5.0.0